AWSTemplateFormatVersion: '2010-09-09'
Description: Backend IaC Configuration

Resources:
  BackendDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounterDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH

  BackendLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VisitorCounterLambdaExecutionRole
      Description: Execution role for the Visitor Counter Lambda function.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VisitorCounterLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource: !GetAtt BackendDatabase.Arn

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  BackendLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VisitorCounterLambda
      Description: Lambda function to increment visitor counter stored in DynamoDB
      Runtime: python3.12
      Handler: lambda_handler
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      PackageType: Zip
      Code:
        ZipFile: |
          import boto3
          import os

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table(os.environ["TABLE_NAME"])

          def lambda_handler(event, context):
              try:
                  table.update_item(
                      Key={"Id": "visitor_count"},
                      UpdateExpression="ADD views :inc",
                      ExpressionAttributeValues={":inc": 1}
                  )
                  return {"statusCode": 200, "body": "Visitor counted"}
              except Exception as e:
                  return {"statusCode": 500, "body": str(e)}
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref BackendDatabase

  BackendApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: VisitorCounterAPI
      Description: HTTP API for the Visitor Counter frontend
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "https://best-resume-ever.com"
        AllowMethods:
          - GET
        AllowHeaders:
          - "*"
      IpAddressType: DUALSTACK

  BackendLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BackendApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt BackendLambdaFunction.Arn
      PayloadFormatVersion: "2.0"
      Description: Lambda proxy integration for visitor counter API

  BackendApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BackendApi
      RouteKey: "GET /visitor"
      Target: !Sub "integrations/${BackendLambdaIntegration}"

  BackendLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BackendLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BackendApi}/*/*/visitor"
      SourceAccount: !Ref "AWS::AccountId"