AWSTemplateFormatVersion: '2010-09-09'
Description: Backend IaC Configuration with GET and POST support

Resources:
  BackendDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounterDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH

  BackendLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VisitorCounterLambdaExecutionRole
      Description: Execution role for the Visitor Counter Lambda function.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VisitorCounterLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource: !GetAtt BackendDatabase.Arn

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  BackendLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VisitorCounterLambda
      Description: Lambda function to handle GET (read) and POST (increment) for visitor count
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      PackageType: Zip
      Code:
        ZipFile: |
          import boto3

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table("VisitorCounterDB")

          def lambda_handler(event, context):
              method = event.get("requestContext", {}).get("http", {}).get("method", "GET")
              try:
                  if method == "POST":
                      response = table.update_item(
                          Key={"Id": "visitor_count"},
                          UpdateExpression="SET #c = if_not_exists(#c, :start) + :inc",
                          ExpressionAttributeNames={"#c": "count"},
                          ExpressionAttributeValues={":inc": 1, ":start": 0},
                          ReturnValues="UPDATED_NEW"
                      )
                  else:
                      response = table.get_item(Key={"Id": "visitor_count"})
                      if "Item" not in response:
                          table.put_item(Item={"Id": "visitor_count", "count": 0})
                          response = {"Item": {"count": 0}}

                  current_count = response.get("Attributes", response.get("Item", {})).get("count", 0)
                  return {"statusCode": 200, "body": str(current_count)}

              except Exception as e:
                  return {"statusCode": 500, "body": f"Error: {str(e)}"}
      Timeout: 10

  BackendApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: VisitorCounterAPI
      Description: HTTP API for the Visitor Counter frontend
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "https://best-resume-ever.com"
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - "*"
      IpAddressType: DUALSTACK

  BackendLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BackendApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt BackendLambdaFunction.Arn
      PayloadFormatVersion: "2.0"
      Description: Lambda proxy integration for visitor counter API

  BackendApiRouteGet:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BackendApi
      RouteKey: "GET /visitor"
      Target: !Sub "integrations/${BackendLambdaIntegration}"

  BackendApiRoutePost:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BackendApi
      RouteKey: "POST /visitor"
      Target: !Sub "integrations/${BackendLambdaIntegration}"

  BackendLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BackendLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${BackendApi}/*/*/visitor"
      SourceAccount: !Ref "AWS::AccountId"

  BackendApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref BackendApi
      StageName: $default
      AutoDeploy: true
      Description: Default stage for Visitor Counter API