AWSTemplateFormatVersion: '2010-09-09'
Description: Backend IaC Configuration

Resources:
  BackendDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounterDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  BackendLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VisitorCounterLambdaExecutionRole
      Description: Execution role for the Visitor Counter Lambda function.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: VisitorCounterLambdaInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt BackendDatabase.Arn
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/VisitorCounterLambda:*"

  BackendLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - BackendLambdaExecutionRole
      - BackendDatabase
    Properties:
      FunctionName: VisitorCounterLambda
      Description: Lambda function to handle GET (read) and POST (increment) for visitor count
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      PackageType: Zip
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: VisitorCounterDB
          ALLOWED_ORIGIN: "https://best-resume-ever.com"
      Code:
        ZipFile: |
          import json
          import os
          import boto3

          TABLE_NAME = os.environ.get("TABLE_NAME", "VisitorCounterDB")
          ALLOWED_ORIGIN = os.environ.get("ALLOWED_ORIGIN", "*")

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table(TABLE_NAME)

          def _get_method(event):
              try:
                  return event.get("httpMethod") or event.get("requestContext", {}).get("http", {}).get("method")
              except Exception:
                  return "GET"

          def _text_response(status, text_body):
              return {
                  "statusCode": status,
                  "headers": {
                      "Content-Type": "text/plain",
                      "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
                      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
                      "Access-Control-Allow-Headers": "*"
                  },
                  "body": str(text_body)
              }

          def lambda_handler(event, context):
              method = _get_method(event) or "GET"
              try:
                  if method == "POST":
                      res = table.update_item(
                          Key={"Id": "visitor_count"},
                          UpdateExpression="SET #c = if_not_exists(#c, :start) + :inc",
                          ExpressionAttributeNames={"#c": "count"},
                          ExpressionAttributeValues={":inc": 1, ":start": 0},
                          ReturnValues="UPDATED_NEW"
                      )
                      count = res.get("Attributes", {}).get("count", 0)
                      return _text_response(200, count)
                  else:
                      res = table.get_item(Key={"Id": "visitor_count"})
                      if "Item" not in res:
                          table.put_item(Item={"Id": "visitor_count", "count": 0})
                          count = 0
                      else:
                          count = res["Item"].get("count", 0)
                      return _text_response(200, count)
              except Exception as e:
                  print("Error:", str(e))
                  return _text_response(500, 0)

  BackendRestApi:
    Type: AWS::ApiGateway::RestApi
    DependsOn:
      - BackendLambdaFunction
    Properties:
      Name: VisitorCounterAPI
      EndpointConfiguration:
        Types: [REGIONAL]

  BackendRestApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    DependsOn:
      - BackendRestApi
    Properties:
      RestApiId: !Ref BackendRestApi
      ParentId: !GetAtt BackendRestApi.RootResourceId
      PathPart: visitor

  BackendRestApiGetMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - BackendRestApiGatewayResource
      - BackendLambdaFunction
    Properties:
      RestApiId: !Ref BackendRestApi
      ResourceId: !Ref BackendRestApiGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendLambdaFunction.Arn}/invocations

  BackendRestApiPostMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - BackendRestApiGatewayResource
      - BackendLambdaFunction
    Properties:
      RestApiId: !Ref BackendRestApi
      ResourceId: !Ref BackendRestApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendLambdaFunction.Arn}/invocations

  BackendRestApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - BackendRestApiGatewayResource
    Properties:
      RestApiId: !Ref BackendRestApi
      ResourceId: !Ref BackendRestApiGatewayResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'*'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'https://best-resume-ever.com'"
            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  BackendRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - BackendRestApiGetMethod
      - BackendRestApiPostMethod
      - BackendRestApiOptionsMethod
    Properties:
      RestApiId: !Ref BackendRestApi
      Description: Deployment for VisitorCounterAPI

  BackendRestApiStage:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - BackendRestApiDeployment
    Properties:
      StageName: prod
      RestApiId: !Ref BackendRestApi
      DeploymentId: !Ref BackendRestApiDeployment
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 50
          ThrottlingRateLimit: 100

  BackendLambdaRestPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - BackendRestApiStage
      - BackendLambdaFunction
    Properties:
      FunctionName: !Ref BackendLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/visitor"
      SourceAccount: !Ref "AWS::AccountId"

  BackendWAFWebACL:
    Type: AWS::WAFv2::WebACL
    DependsOn:
      - BackendRestApiStage
    Properties:
      Name: ApiWAF
      Description: WAF for the visitor counter API Gateway
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: ApiWAF
        SampledRequestsEnabled: true
      Rules:
        - Name: RateLimit500Per5MinPerIP
          Priority: 1
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 500
              AggregateKeyType: IP
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: RateLimit500Per5MinPerIP
            SampledRequestsEnabled: true

        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 10
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: true

        - Name: AWS-AWSManagedRulesBotControlRuleSet
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesBotControlRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesBotControlRuleSet
            SampledRequestsEnabled: true

  BackendWAFWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - BackendWAFWebACL
      - BackendRestApiStage
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${BackendRestApi}/stages/prod"
      WebACLArn: !GetAtt BackendWAFWebACL.Arn