AWSTemplateFormatVersion: '2010-09-09'
Description: Backend IaC Configuration

Resources:
  BackendDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounterDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH