AWSTemplateFormatVersion: '2010-09-09'
Description: Backend IaC Configuration

Resources:
  BackendDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounterDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH

  BackendLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VisitorCounterLambdaExecutionRole
      Description: Execution role for the Visitor Counter Lambda function.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VisitorCounterLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource: !GetAtt BackendDatabase.Arn

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  BackendLambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: crc-backend-lambda-code
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30

  BackendLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VisitorCounterLambda
      Description: Lambda function to increment visitor counter stored in DynamoDB
      Runtime: python3.12
      Handler: app.lambda_handler
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      PackageType: Zip
      Code:
        S3Bucket: !Ref BackendLambdaCodeBucket
        S3Key: lambda.zip
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref BackendDatabase