AWSTemplateFormatVersion: '2010-09-09'
Description: Backend IaC Configuration

Resources:
  BackendDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounterDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  BackendLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VisitorCounterLambdaExecutionRole
      Description: Execution role for the Visitor Counter Lambda function
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: VisitorCounterLambdaInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt BackendDatabase.Arn
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/VisitorCounterLambda:*"

  BackendLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - BackendLambdaExecutionRole
      - BackendDatabase
    Properties:
      FunctionName: VisitorCounterLambda
      Description: Lambda function to handle GET (read) and POST (increment) for visitor count
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt BackendLambdaExecutionRole.Arn
      PackageType: Zip
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: VisitorCounterDB
          ALLOWED_ORIGIN: "https://best-resume-ever.com"
      Code:
        ZipFile: |
          import json
          import os
          import boto3

          TABLE_NAME = os.environ.get("TABLE_NAME", "VisitorCounterDB")
          ALLOWED_ORIGIN = os.environ.get("ALLOWED_ORIGIN", "*")

          dynamodb = boto3.resource("dynamodb")
          table = dynamodb.Table(TABLE_NAME)

          def _get_method(event):
              try:
                  return event.get("httpMethod") or event.get("requestContext", {}).get("http", {}).get("method")
              except Exception:
                  return "GET"

          def _text_response(status, text_body):
              return {
                  "statusCode": status,
                  "headers": {
                      "Content-Type": "text/plain",
                      "Access-Control-Allow-Origin": ALLOWED_ORIGIN,
                      "Access-Control-Allow-Methods": "GET,POST,OPTIONS",
                      "Access-Control-Allow-Headers": "'Content-Type'"
                  },
                  "body": str(text_body)
              }

          def lambda_handler(event, context):
              method = _get_method(event) or "GET"
              try:
                  if method == "POST":
                      res = table.update_item(
                          Key={"Id": "visitor_count"},
                          UpdateExpression="SET #c = if_not_exists(#c, :start) + :inc",
                          ExpressionAttributeNames={"#c": "count"},
                          ExpressionAttributeValues={":inc": 1, ":start": 0},
                          ReturnValues="UPDATED_NEW"
                      )
                      count = res.get("Attributes", {}).get("count", 0)
                      return _text_response(200, count)
                  else:
                      res = table.get_item(Key={"Id": "visitor_count"})
                      if "Item" not in res:
                          table.put_item(Item={"Id": "visitor_count", "count": 0})
                          count = 0
                      else:
                          count = res["Item"].get("count", 0)
                      return _text_response(200, count)
              except Exception as e:
                  print("Error:", str(e))
                  return _text_response(500, 0)

  BackendRestApi:
    Type: AWS::ApiGateway::RestApi
    DependsOn:
      - BackendLambdaFunction
    Properties:
      Name: VisitorCounterAPI
      EndpointConfiguration:
        Types: [REGIONAL]

  BackendRestApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    DependsOn:
      - BackendRestApi
    Properties:
      RestApiId: !Ref BackendRestApi
      ParentId: !GetAtt BackendRestApi.RootResourceId
      PathPart: visitor

  BackendRestApiGetMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - BackendRestApiGatewayResource
      - BackendLambdaFunction
    Properties:
      RestApiId: !Ref BackendRestApi
      ResourceId: !Ref BackendRestApiGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendLambdaFunction.Arn}/invocations

  BackendRestApiPostMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - BackendRestApiGatewayResource
      - BackendLambdaFunction
    Properties:
      RestApiId: !Ref BackendRestApi
      ResourceId: !Ref BackendRestApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BackendLambdaFunction.Arn}/invocations

  BackendRestApiOptionsMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - BackendRestApiGatewayResource
    Properties:
      RestApiId: !Ref BackendRestApi
      ResourceId: !Ref BackendRestApiGatewayResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'https://best-resume-ever.com'"
            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  BackendRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - BackendRestApiGetMethod
      - BackendRestApiPostMethod
      - BackendRestApiOptionsMethod
    Properties:
      RestApiId: !Ref BackendRestApi
      Description: Deployment for REST API

  BackendRestApiStage:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - BackendRestApiDeployment
    Properties:
      StageName: prod
      RestApiId: !Ref BackendRestApi
      DeploymentId: !Ref BackendRestApiDeployment
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 50
          ThrottlingRateLimit: 100

  BackendLambdaRestPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - BackendRestApiStage
      - BackendLambdaFunction
    Properties:
      FunctionName: !Ref BackendLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/visitor"
      SourceAccount: !Ref "AWS::AccountId"

  BackendMonitoringAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: monitoring-alert-topic
      KmsMasterKeyId: alias/aws/sns

  BackendMonitoringAlertEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: f.ermenkov@gmail.com
      TopicArn: !Ref BackendMonitoringAlertTopic

  BackendLambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: lambda-errors-alarm
      AlarmDescription: Triggered when Backend Lambda throws errors.
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref BackendLambdaFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref BackendMonitoringAlertTopic
      TreatMissingData: notBreaching

  BackendApiLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: api-latency-alarm
      AlarmDescription: API latency exceeded threshold (p90).
      Namespace: AWS/ApiGateway
      MetricName: Latency
      Dimensions:
        - Name: ApiId
          Value: !Ref BackendRestApi
        - Name: Stage
          Value: prod
      ExtendedStatistic: p90
      Period: 60
      EvaluationPeriods: 2
      Threshold: 800
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref BackendMonitoringAlertTopic
      TreatMissingData: notBreaching

  BackendLambdaInvocationsSpikeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: lambda-invocations-spike-alarm
      AlarmDescription: Sudden spike in Lambda invocations.
      Namespace: AWS/Lambda
      MetricName: Invocations
      Dimensions:
        - Name: FunctionName
          Value: !Ref BackendLambdaFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 25
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref BackendMonitoringAlertTopic
      TreatMissingData: notBreaching

  BackendWAFBlockedRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: waf-blocked-requests-alarm
      AlarmDescription: High number of requests blocked by WAF.
      Namespace: AWS/WAFV2
      MetricName: BlockedRequests
      Dimensions:
        - Name: WebACL
          Value: !Ref BackendWAFWebACL
        - Name: Region
          Value: us-east-1
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref BackendMonitoringAlertTopic
      TreatMissingData: notBreaching

  BackendBillingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: billing-alarm
      AlarmDescription: Estimated charges exceed $50.
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: USD
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref BackendMonitoringAlertTopic
      TreatMissingData: notBreaching

  BackendMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: MonitoringDashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Errors",
                "metrics": [
                  [ "AWS/Lambda", "Errors", "FunctionName", "${BackendLambdaFunction}" ]
                ],
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${BackendLambdaFunction}" ]
                ],
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "title": "API Latency (p90)",
                "metrics": [
                  [ "AWS/ApiGateway", "Latency", "ApiId", "${BackendRestApi}", "Stage", "prod", { "stat": "p90" } ]
                ],
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "title": "WAF Blocked Requests",
                "metrics": [
                  [ "AWS/WAFV2", "BlockedRequests", "WebACL", "${BackendWAFWebACL}", "Region", "us-east-1" ]
                ],
                "stat": "Sum",
                "region": "us-east-1"
              }
            },
            {
              "type": "metric",
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Estimated Billing (USD)",
                "metrics": [
                  [ "AWS/Billing", "EstimatedCharges", "Currency", "USD" ]
                ],
                "stat": "Maximum",
                "region": "us-east-1"
              }
            }
          ]
        }

  BackendUnusedAccessAnalyzer:
    Type: AWS::AccessAnalyzer::Analyzer
    Properties:
      AnalyzerConfiguration: 
        UnusedAccessConfiguration:
          UnusedAccessAge: 1
      AnalyzerName: UnusedAccessAnalyzer
      Type: ACCOUNT_UNUSED_ACCESS

  BackendWAFWebACL:
    Type: AWS::WAFv2::WebACL
    DependsOn:
      - BackendRestApiStage
    Properties:
      Name: ApiWAF
      Description: WAF for the visitor counter API Gateway
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: ApiWAF
        SampledRequestsEnabled: true
      Rules:
        - Name: RateLimit500Per5MinPerIP
          Priority: 1
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 500
              AggregateKeyType: IP
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: RateLimit500Per5MinPerIP
            SampledRequestsEnabled: true

        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 10
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: true

        - Name: AWS-AWSManagedRulesBotControlRuleSet
          Priority: 20
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesBotControlRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesBotControlRuleSet
            SampledRequestsEnabled: true

  BackendWAFWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - BackendWAFWebACL
      - BackendRestApiStage
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${BackendRestApi}/stages/prod"
      WebACLArn: !GetAtt BackendWAFWebACL.Arn