AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend Infrastructure Configuration

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: crc-frontend-bucket
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
          - Id: AbortIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  FrontendCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: best-resume-ever.com
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: best-resume-ever.com
          HostedZoneId: Z065821612PL5JPWWEB99
      KeyAlgorithm: RSA_2048

  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: FrontendOAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  FrontendCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - best-resume-ever.com
        DefaultRootObject: website/pages/main/main.html
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_100
        Origins:
          - Id: S3FrontendOrigin
            DomainName: !GetAtt FrontendBucket.DomainName
            OriginAccessControlId: !Ref FrontendOAC
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3FrontendOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
        ViewerCertificate:
          AcmCertificateArn: !Ref FrontendCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /website/pages/main/main.html
            ResponseCode: 200
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponsePagePath: /website/pages/main/main.html
            ResponseCode: 200
            ErrorCachingMinTTL: 300

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendCloudFrontDistribution}"

  FrontendDNSRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z065821612PL5JPWWEB99
      RecordSets:
        - Name: best-resume-ever.com
          Type: A
          AliasTarget:
            DNSName: !GetAtt FrontendCloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: best-resume-ever.com
          Type: AAAA
          AliasTarget:
            DNSName: !GetAtt FrontendCloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2

  FrontendDNSSECKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: DNSSEC KSK signing key for best-resume-ever.com
      Enabled: true
      KeyUsage: SIGN_VERIFY
      KeySpec: ECC_SECG_P256K1
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAccountAdmin
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

          - Sid: AllowRoute53DNSSEC
            Effect: Allow
            Principal:
              Service: route53.amazonaws.com
            Action:
              - kms:DescribeKey
              - kms:GetPublicKey
              - kms:Sign
            Resource: "*"

  # FrontendDNSSECKSK:
  #   Type: AWS::Route53::KeySigningKey
  #   Properties:
  #     HostedZoneId: Z065821612PL5JPWWEB99
  #     KeyManagementServiceArn: !GetAtt FrontendDNSSECKmsKey.Arn
  #     Name: ksk_best_resume_ever
  #     Status: ACTIVE
  #   DependsOn:
  #     - FrontendDNSSECKmsKey

  # FrontendDNSSEC:
  #   Type: AWS::Route53::DNSSEC
  #   Properties:
  #     HostedZoneId: Z065821612PL5JPWWEB99
  #   DependsOn:
  #       - FrontendDNSSECKSK